<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CreativeCoders.Net.XmlRpc" />
        <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CreativeCoders.HomeMatic.Tests" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CreativeCoders.HomeMatic.Core\CreativeCoders.HomeMatic.Core.csproj" />
        <ProjectReference Include="..\CreativeCoders.HomeMatic.JsonRpc\CreativeCoders.HomeMatic.JsonRpc.csproj" />
        <ProjectReference Include="..\CreativeCoders.HomeMatic.XmlRpc\CreativeCoders.HomeMatic.XmlRpc.csproj" />
    </ItemGroup>

</Project>
